- 👋 Hi, I’m @Bankfunds1
- 👀 I’m interested in serving customers and send them money into thier account..and open a website that support all the banking website future and bank funding domain
- 🌱 I’m currently learning ..and i need you all,i will appreciate to have a partner
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...

<!---
Bankfunds1/Bankfunds1 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
